# Generated by Django 3.2.15 on 2022-10-26 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_portfolio_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
