# Generated by Django 3.2.15 on 2022-11-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20221114_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='price',
            new_name='buy_price',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='average_price',
            new_name='current_price',
        ),
        migrations.AddField(
            model_name='asset',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
